services:
  esp32dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esp32dev
    hostname: esp32-dev
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
    volumes:
      - ./workspace:/workspace
      - /dev:/dev:rw
    privileged: true
    annotations:
      run.oci.keep_original_groups: "1"
    restart: unless-stopped
