[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip=esp32c3 --preverify --always-print-stacktrace --no-location --catch-hardfault"

[build]
target = "riscv32imc-unknown-none-elf"
rustflags = ["-C", "force-frame-pointers"]

[unstable]
build-std = ["core"]

[env]
# WiFi configuration for integrated IoT system
WIFI_SSID = "YourWiFiNetwork"
WIFI_PASSWORD = "YourWiFiPassword"

# MQTT broker configuration for integrated IoT system
MQTT_BROKER_IP = "10.10.10.210"
MQTT_BROKER_PORT = "1883"
MQTT_CLIENT_ID = "esp32-c3-main-app"
MQTT_TOPIC_PREFIX = "esp32-iot"
