[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG_LEVEL = "info"
# WiFi credentials - replace with your actual values
SSID = "FamiliaFeliz-2Ghz" 
PASSWORD = "ines#sara"

# Unstable flags needed for ESP32-C3
[unstable]
build-std = ["core", "alloc"]