[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip=esp32c3 --preverify --always-print-stacktrace --no-location --catch-hardfault"

[build]
target = "riscv32imc-unknown-none-elf"
rustflags = ["-C", "force-frame-pointers"]

[unstable]
build-std = ["core"]

[env]
# WiFi Access Point Credentials - UPDATE THESE WITH YOUR NETWORK
WIFI_SSID = "FamiliaFeliz-2Ghz"
WIFI_PASSWORD = "ines#sara"

