[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip=esp32c3 --preverify --always-print-stacktrace --no-location --catch-hardfault --base-address 0x0"

[build]
target = "riscv32imc-unknown-none-elf"
rustflags = ["-C", "force-frame-pointers"]

[unstable]
build-std = ["core"]

[env]
# Default WiFi credentials (can be overridden)
WIFI_SSID = "ESP32-Test"
WIFI_PASSWORD = "password123"

# Default MQTT configuration
MQTT_BROKER_IP = "192.168.1.100"
MQTT_BROKER_PORT = "1883"
MQTT_CLIENT_ID = "esp32-c3-console"
MQTT_TOPIC_PREFIX = "esp32"